# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1445c808f6db36fba859603c99988f76"
name = "All-In-One Store"
handle = "all-in-one-store"
application_url = "https://contacted-wins-briefly-acres.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "droptrackingapp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://contacted-wins-briefly-acres.trycloudflare.com/auth/callback",
  "https://contacted-wins-briefly-acres.trycloudflare.com/auth/shopify/callback",
  "https://contacted-wins-briefly-acres.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
