# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30e55710145993ddb5716e3a7c3e50c3"
name = "droptracking-dev"
handle = "droptracking-dev"
application_url = "https://deliver-tree-carbon-relate.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-all-in-one-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_locales,read_online_store_pages,read_orders,read_products,read_script_tags,read_themes,write_content,write_online_store_pages,write_script_tags"

[auth]
redirect_urls = [
  "https://deliver-tree-carbon-relate.trycloudflare.com/auth/callback",
  "https://deliver-tree-carbon-relate.trycloudflare.com/auth/shopify/callback",
  "https://deliver-tree-carbon-relate.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
