# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1445c808f6db36fba859603c99988f76"
name = "All-In-One Store"
handle = "all-in-one-store"
application_url = "https://manner-pubmed-solved-pool.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testing-aios.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://manner-pubmed-solved-pool.trycloudflare.com/auth/callback",
  "https://manner-pubmed-solved-pool.trycloudflare.com/auth/shopify/callback",
  "https://manner-pubmed-solved-pool.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  uri = "https://all-in-one-store-u65ap.ondigitalocean.app/webhooks"
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]

[app_proxy]
url = "https://manner-pubmed-solved-pool.trycloudflare.com/api"
subpath = "aios"
prefix = "a"

[pos]
embedded = false
