# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1445c808f6db36fba859603c99988f76"
name = "All-In-One Store"
handle = "all-in-one-store"
application_url = "https://showers-architecture-proud-packages.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "droptrackingapp.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://showers-architecture-proud-packages.trycloudflare.com/auth/callback",
  "https://showers-architecture-proud-packages.trycloudflare.com/auth/shopify/callback",
  "https://showers-architecture-proud-packages.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[app_proxy]
url = "https://showers-architecture-proud-packages.trycloudflare.com/api"
subpath = "aios"
prefix = "a"

[pos]
embedded = false
