# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30e55710145993ddb5716e3a7c3e50c3"
name = "droptracking-dev"
handle = "droptracking-dev"
application_url = "https://bar-corp-morgan-become.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "droptrackingapp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_locales,read_online_store_pages,read_orders,read_products,read_script_tags,read_themes,write_content,write_discounts,write_online_store_pages,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://bar-corp-morgan-become.trycloudflare.com/auth/callback",
  "https://bar-corp-morgan-become.trycloudflare.com/auth/shopify/callback",
  "https://bar-corp-morgan-become.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://bar-corp-morgan-become.trycloudflare.com/api"
subpath = "aios"
prefix = "a"

[pos]
embedded = false
